import {
  AlertCircle,
  Award,
  Badge,
  Bell,
  Bitcoin,
  Bolt,
  Book,
  Briefcase,
  Building,
  CalendarCheck,
  Captions,
  CheckCircle,
  Code,
  Codepen,
  Coffee,
  File as DocumentIcon,
  Euro,
  Eye,
  File,
  FileQuestion,
  FileText,
  Flag,
  Ghost,
  Gift,
  Grid,
  Heart,
  HelpCircle,
  Kanban,
  Key,
  Layout,
  LayoutGrid,
  LifeBuoy,
  MessageSquare,
  Monitor,
  Network,
  Users as PeopleIcon,
  Plug,
  ScrollText,
  Settings,
  Share2,
  Shield,
  ShieldUser,
  ShoppingCart,
  SquareMousePointer,
  Star,
  Theater,
  TrendingUp,
  UserCheck,
  UserCircle,
  Users,
  Briefcase as WorkIcon,
  Zap,
} from 'lucide-react';
import { type MenuConfig } from './types';

export const MENU_SIDEBAR: MenuConfig = [
  {
    title: 'Dashboard',
    path: '/public-profile/profiles/gamer',
  },
  {
    title: 'Analisis',
    path: '/analisis',
  },
  {
    title: 'History',
    path: '/history',
  },
];

//   {
//     title: 'Getting Started',
//     icon: Coffee,
//     path: 'https://keenthemes.com/metronic/tailwind/docs/getting-started/installation',
//   },
//   {
//     title: 'Support Forum',
//     icon: AlertCircle,
//     children: [
//       {
//         title: 'All Questions',
//         icon: FileQuestion,
//         path: 'https://devs.keenthemes.com',
//       },
//       {
//         title: 'Popular Questions',
//         icon: Star,
//         path: 'https://devs.keenthemes.com/popular',
//       },
//       {
//         title: 'Ask Question',
//         icon: HelpCircle,
//         path: 'https://devs.keenthemes.com/question/create',
//       },
//     ],
//   },
//   {
//     title: 'Licenses & FAQ',
//     icon: Captions,
//     path: 'https://keenthemes.com/metronic/tailwind/docs/getting-started/license',
//   },
//   {
//     title: 'Documentation',
//     icon: FileQuestion,
//     path: 'https://keenthemes.com/metronic/tailwind/docs',
//   },
//   { separator: true },
//   { title: 'Contact Us', icon: Share2, path: 'https://keenthemes.com/contact' },
// ];
